spring.application.name=onlineStore
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=jah.lau319
spring.datasource.url=jdbc:mysql://localhost:3306/online_store?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false